Update oc_couples.lsl to add partner controlled couples pose system to remove legacy ask box if both individuals have access
OpenCollarTeam/OpenCollar pull request #1042
Opened 2024-05-05 03:25 UTC by RosalynRussell

Adds a system to initiate a couples pose without the permission box if the receiver trusts the initiator.

2024-05-05 03:30 UTC, Medea-Destiny commented
Note for testers, this will require the oc_api script that's in 8.3 features branch to test as it's dependant on that.

2024-05-05 04:16 UTC, RosalynRussell commented
Testers: Verify all combinations of trusted, owned, and no relation couples to make sure that the permissions box is used when appropriate, and bypassed when appropriate.

2024-05-06 13:34 UTC, Pingout commented
I disagree with the idea of this feature. Essentially every time my sub wants a hug I automatically hug them? You are removing my option to *not* be dominated by my submissive

2024-05-06 15:05 UTC, RosalynRussell commented
> I disagree with the idea of this feature. Essentially every time my sub wants a hug I automatically hug them? You are removing my option to _not_ be dominated by my submissive

This only applies to trusted or owning individuals. If you don't set a sub as trusted, they will still ask via permission box. Nothing stops a trusted submissive asking in chat before doing it. And in a D/s sense, if your submissive is doing things they shouldn't, there are ways to correct them.

2024-05-06 15:12 UTC, SilkieSabra commented
I think that allowing an automated couples where the wearer can initiate and the owner has no ability to refuse, or even wait before accepting, is a bad idea.  The couples system has a long time before the popup times out for a reason.  I am a sub in a poly family.  When my Master arrives there might be three to five of us initiating a footkiss.  We can't see who else has initiated the animation.  The owner controls the choice of who to respond to first and who has to wait their turn.  Without this feature there would be a pile-up.

2024-05-07 01:09 UTC, RosalynRussell commented
I will inquire what would be involved with adding a toggle within the menu to disable or enable the feature.

2024-05-20 12:59 UTC, RosalynRussell commented
In adding a setting toggle a bug was found when trust is not mutual, this will be resolved.

2024-05-29 16:30 UTC, Pingout reviewed
I could not make this work at all.
I had the collar Wearer put both this script and the oc_api script from 8.3 features branch into their collar. Both the Wearer and the Owner (me) were able to toggle the "Auto" button, but it had no effect. I continued to get the *Wearer* invited you to a couples animation! Click [Yes] to accept, no matter what configuration we used. 
Please let me know if I'm missing something. Thank you.

2024-05-30 02:32 UTC, RosalynRussell commented
> I could not make this work at all. I had the collar Wearer put both this script and the oc_api script from 8.3 features branch into their collar. Both the Wearer and the Owner (me) were able to toggle the "Auto" button, but it had no effect. I continued to get the _Wearer_ invited you to a couples animation! Click [Yes] to accept, no matter what configuration we used. Please let me know if I'm missing something. Thank you.

The recipient must trust the initiator, and the recipient is who must have auto enabled. You message was unclear if you trusted the person trying to start an animation with you, and if you had auto enabled. It is auto-accept, on the receivers end.

2024-05-30 12:50 UTC, Pingout commented
> 
> The recipient must trust the initiator, and the recipient is who must have auto enabled. You message was unclear if you trusted the person trying to start an animation with you, and if you had auto enabled. It is auto-accept, on the receivers end.

The situation I discribed had a collar Wearer, and a collar Owner. 
As I stated, we tried every conceiveable combination of "Wearer Initiated animation, Owner Initiated animation, Owner checking and unchecking the Auto Box, and Wearer checking or unchecing the Auto box.
Are you saying this does not work for Owner, that it only works for Trusted?
When I am saying Owner, I mean CMD_OWNER as indicated in the script. The 500. So in my mind, when you say "Trust" or "Trusted" you mean CMD_TRUSTED, or the 501 value. If you have another meaning for "Trust", that may be where our disconnect is. 

Please define "Trust" and "Trusted"

Also, there is an aparent problem with the checkbox being enabled from both the Wearer and the Owner. In your comment above you said the recipient must have Auto enabled. But the Wearer (initiator) can check the Auto box and have it reflect in the Owner (receiver) menu. The collar wearer should not be able to set Auto.

2024-05-30 13:33 UTC, RosalynRussell commented
> > The recipient must trust the initiator, and the recipient is who must have auto enabled. You message was unclear if you trusted the person trying to start an animation with you, and if you had auto enabled. It is auto-accept, on the receivers end.
> 
> The situation I discribed had a collar Wearer, and a collar Owner. As I stated, we tried every conceiveable combination of "Wearer Initiated animation, Owner Initiated animation, Owner checking and unchecking the Auto Box, and Wearer checking or unchecing the Auto box. Are you saying this does not work for Owner, that it only works for Trusted? When I am saying Owner, I mean CMD_OWNER as indicated in the script. The 500. So in my mind, when you say "Trust" or "Trusted" you mean CMD_TRUSTED, or the 501 value. If you have another meaning for "Trust", that may be where our disconnect is.
> 
> Please define "Trust" and "Trusted"
> 
> Also, there is an aparent problem with the checkbox being enabled from both the Wearer and the Owner. In your comment above you said the recipient must have Auto enabled. But the Wearer (initiator) can check the Auto box and have it reflect in the Owner (receiver) menu. The collar wearer should not be able to set Auto.

'if (iNum >= CMD_OWNER && iNum <= CMD_EVERYONE) {" is who gets to issue an auto pose request, ie the same people who could do "/1 you hug me". What happens if the Initiator's collar sends a message to the Recipient's collar. If the Initiator has access to the Recipient's collar, the Recipient's collar will send a message back, either a silent "pong" (yes, go for auto) or an error message "Not in Auto" (falling back to legacy) or "Busy", both reflected in the message the Initiator gets. If no "pong" is received after 2.5 seconds the Initiator collar decides that either the Recipient has no valid collar or that the Initiator has no access to the Recipient. It then fully falls back to old code.

I am not sure what you are saying about setting the toggle. Only the Recipient must have it enabled for auto to work (ie send "pong" not "autooff", and "if (iAuth==CMD_OWNER || kAv==g_kWearer)" can toggle it.

2024-05-31 02:00 UTC, Pingout commented
You are defining "trust" as someone with Access, yes? I attempted to initiate a couples pose in every possible type of access. The script did nothing different than a normal Couples pose.

And this is not right: "if (iAuth==CMD_OWNER || kAv==g_kWearer)" can toggle it. The collar wearer should not be able to set Auto

There is a posibility that lag is interfering with the script, but the animation seems to work within the 2-1/2 second window. 

Maybe if we talk inworld? There does seem to be a communication problem here. Inworld I am Pingout Duffield

2024-06-02 15:53 UTC, RosalynRussell commented
> You are defining "trust" as someone with Access, yes? I attempted to initiate a couples pose in every possible type of access. The script did nothing different than a normal Couples pose.
> 
> And this is not right: "if (iAuth==CMD_OWNER || kAv==g_kWearer)" can toggle it. The collar wearer should not be able to set Auto
> 
> There is a posibility that lag is interfering with the script, but the animation seems to work within the 2-1/2 second window.
> 
> Maybe if we talk inworld? There does seem to be a communication problem here. Inworld I am Pingout Duffield

I'm unfortunately out of town for a little over a week and not able to get into SL. Once I return, certainly. For now, let me explain my setup that does work to check for discrepancies. I have a slave, Lily. On her collar, Auto is on and I am her owner. On my collar, Auto is on, and she is Trusted. Either of us can start an animation and the other auto accepts. It has worked great several days before I left on this trip, so clearly something is not correct in you and your slave's collars. Not sure how to test without meeting and enabling some debug messages in my collar to see exactly how your collar is responding to my pings if I initiate or sending them out to mine if you initiate.

2024-06-02 16:37 UTC, Pingout commented
I see a problem. I'm not wearing a collar.

Does the script only work when both participants are wearing collars?

2024-06-03 06:09 UTC, RosalynRussell commented
> I see a problem. I'm not wearing a collar.
> 
> Does the script only work when both participants are wearing collars?

Oh, yes! It's auto accept for requests that come to you, so instead of their collar animating you (needing permission), their collar tells your collar to animate you. (Similar concept to an RLV relay tbh.) It only works if both people have the new script, messages go back and forth several times.

2024-06-05 13:26 UTC, SilkieSabra commented
We can't have a feature as standard that does not work unless both parties are wearing  collars.  Everything else in the collar works with owners who are not also wearers, which is I would say the majority of collar owners.

2024-06-06 05:01 UTC, RosalynRussell commented
> We can't have a feature as standard that does not work unless both parties are wearing collars. Everything else in the collar works with owners who are not also wearers, which is I would say the majority of collar owners.

SL limitation, honestly. Before I got in contact with Medea I looked first into any way I could set my viewer to auto accept animation requests, getting in touch with Firestorm support, and there simply is not, and honestly for good reason. Your collar cannot animate me without the pop up box under any circumstances. The only way is a relay situation. It seems something is indicating the flow backwards. It might be the toggle button name. It is auto ACCEPT, incoming, recipient only setting. You can't send a couples pose request unless you have a collar though, so it's not a feature you directly have access to? Without a collar, I can't send my slave a hug request for her to accept manually or automatically. That said, and this was not closely looked at as I don't personally use it, but Medea did mention the possibility of putting it in the Dominant hud. Is couples a function of that hud already? Access to couples animations is a good part of why I wear an invisible open collar even when in full domme mode.

2024-06-06 15:48 UTC, SilkieSabra commented
I remember when that safeguard was implemented and it was precisely because of the abuse potential that was being widely exploited by scripted forced animation devices.  You are looking for a way to enable this in the collar, which can't be done for the owner unless the owner is wearing an object that grants the permission.  I think this is a perfect opportunity for a third party app or addon.

2024-06-07 05:55 UTC, RosalynRussell commented
> I remember when that safeguard was implemented and it was precisely because of the abuse potential that was being widely exploited by scripted forced animation devices. You are looking for a way to enable this in the collar, which can't be done for the owner unless the owner is wearing an object that grants the permission. I think this is a perfect opportunity for a third party app or addon.

Oh, I get why the safeguard is there, and agree it should be there.

As for my edits here, I did start as a separate, potentially addon, script, Medea told me to just put it into oc_couples. I dunno if you are seeing this @Medea-Destiny , if so, can you chime in and confirm I read you right on that?

(I will be returning from trip and back to SL in  4 days.)

2024-06-13 02:19 UTC, Medea-Destiny commented
Ok, lemme explain things a bit.

An attachment you are wearing can animate you without a requester. An attachment someone else is wearing cannot. This is an SL thing.

So, someone asks a collar wearer to hug them. The collar checks to see if they have the authority to do so, and if they do, the target's collar has to request animation permission from that person so that it can make them play the other side of the couple animation.

The concept behind this change is that the wearer's collar will then check to see if the person issuing that command, with sufficient auth level to request a couple animation, also has a collar. If that person does, it will respond to the collar saying so, and can then initiate the second half of the couple animation without a requester being sent, because the animation now comes from that person's own attachment, not another person's attachment.

Security: the requirement for both to have MUTUAL access is exactly to avoid this kind of issue. The idea is that this cannot be used as a backdoor attack, you'd have to have permission to access someone's collar anyway.

Utility: While this does currently require both people to wear a collar, this is not as rare a situation as might be considered at first. Many people mutually trust each other on their collars. There's also the possibility ordering two of their subs to hug each other, which currently requires one of their subs to click accept, which obviously contradicts the control of the dominant.
Moreover, this is something we can now add into the owner hud, which will mean that if a dominant issues a hug command to a submissive via their owner hud, the owner hud could handle their side of the animation.

2024-06-14 17:53 UTC, SilkieSabra commented
Many people but not all and not even most.  Most doms shudder at the idea of wearing a collar.  Maybe you could fashion it so the remote would do this.

2024-06-17 02:26 UTC, Medea-Destiny commented
Adding it into the remote is the plan, but it needs to be in the collar first!

2024-06-23 22:30 UTC, SilkieSabra commented
If there is no way to have this in the remote without also having it in the collar first--then is there a way to prevent it showing as an option for an owner unless the owner is wearing a collar? Or failing that to make a prominent note in the menu saying OWNER MUST WEAR A COLLAR FOR THIS TO WORK.

2024-06-24 03:53 UTC, RosalynRussell commented
> If there is no way to have this in the remote without also having it in the collar first--then is there a way to prevent it showing as an option for an owner unless the owner is wearing a collar? Or failing that to make a prominent note in the menu saying OWNER MUST WEAR A COLLAR FOR THIS TO WORK.

It only showing as an option if the owner has a collar makes no sense and would probably be a nightmare to try code. Especially for a self-own, like myself (and first startup on every collar). The criteria for auto-accept is that the receiver has a collar. The receiver has a collar or it wouldn't be an option for the reciever. If you have no collar, you cannot send an OC pose request to the collar wearer to be accepted manually or automatically, so it makes zero difference if it is on or off. It doesn't matter if I would answer my phone or not if you have no phone to call me with in the first place. And as Medea mentioned, ordering two subs to pose would be doable even if the owner has no collar. The option is 100% receiver side. It's if you will auto-accept OC couples poses from people you trust. It's whether or not the wearer's collar picks up the phone, and it makes no difference if no one is calling. If I am near you, and you type /1 si hug ro, unless YOU have an OC collar, NOTHING WILL HAPPEN. It does not matter if I have no collar, a collar without this code, one with it but off, or one with it in auto. You can't send me a OC couple pose request in any fashion. How can we make this clearer to end users that it is RECIEVING couples poses that are auto, not outgoing? That's the real issue here.

2024-06-25 20:24 UTC, SilkieSabra commented
What I am concerned about is that the party at either end of the call will expect something to happen, and nothing happens.  That's the recipe for one of those support calls starting "it didn't work".

2024-06-26 03:40 UTC, RosalynRussell commented
> What I am concerned about is that the party at either end of the call will expect something to happen, and nothing happens. That's the recipe for one of those support calls starting "it didn't work".

In any case where something happens today, that thing will still happen. If I type /1 ro hug si, and you have no collar, or have auto off, it will ask you the way it always did before, with the pop-up. This adds nothing new per se to oc_couples, just makes it so you don't get the popup if someone you trust tries to animate you, providing you have auto-accept on. But neither of us should be expecting that if we type /1 si hug ro that anything will happen. If we do, there's been a critical misunderstanding of Open Collar prefixes.

2024-06-26 13:35 UTC, Pingout commented
It's been very difficult to communicate that this will be a problem for Support Staff, and also a problem in general. We absolutely understand how you intend it to work. 
We tell you that, as intended, there will be problems with this, and you refuse to see that there might be a problem and then tell us again how it's supposed to work.
I can assure you that we do not have any sort of misunderstanding of how OpenCollar Prefixes work. I can not speak for other people who have expressed concerns, but for myself I have been using and building OpenCollar for a decade. You are not dealing with OpenCollar newcomers here, we have been working as Support staff, answering questions and solving problems in the Support channel for years and years.
Forgive me if I sound upset, but it's been extremely frustrating trying to communicate our concerns. Please stop looking at what you think we are saying, and read our concerns carefully, and try to understand what we see will happen when this change is implemented.

2024-06-26 14:06 UTC, RosalynRussell commented
> It's been very difficult to communicate that this will be a problem for Support Staff, and also a problem in general. We absolutely understand how you intend it to work. We tell you that, as intended, there will be problems with this, and you refuse to see that there might be a problem and then tell us again how it's supposed to work. I can assure you that we do not have any sort of misunderstanding of how OpenCollar Prefixes work. I can not speak for other people who have expressed concerns, but for myself I have been using and building OpenCollar for a decade. You are not dealing with OpenCollar newcomers here, we have been working as Support staff, answering questions and solving problems in the Support channel for years and years. Forgive me if I sound upset, but it's been extremely frustrating trying to communicate our concerns. Please stop looking at what you think we are saying, and read our concerns carefully, and try to understand what we see will happen when this change is implemented.

I'm going to use John and Jane (jo and ja) from now on so it's clear I'm talking about end users doing things, and not us here. I was not trying to say any of us misunderstand OC prefixes, we all know the first prefix after /1 (or at all if channel 0 is used) is whose collar is controlled, I meant if we were end users making that mistake, it was a massive misunderstanding on the end user's part, and given how long prefixes have been a thing, unlikely.

Genuinely, what do you think people will get wrong?

The only thing I can come up with, and while I thought it would be a stretch, it's what you did early in testing, and that is Jane thinking if she turns on Auto in her collar (Or John turns it on for her), and she or he types /1 ja hug jo, that he will automatically walk up and hug John. That's a stretch due to SL animation permissions being how they have been for so long (as long as I've been around, six some years). The workaround is to make it clearer it's auto ACCEPT.  "▢ Auto Accept" is too long for SL Dialog boxes though. I could see if abbreviating it, to say "▢ Auto Acpt" or such would fit, but it does seem there isn't consensus on shortening Accept, I find both "Acpt" and "Acc" Googling it. Which would you prefer, or do you have a better idea to make it clear it's (in effect) automatically accepting the permission popup from people with collar access? "▢ Auto Accept from Trusted or Owner" is far, far too long.

2024-06-26 18:31 UTC, SilkieSabra commented
Let's say Jane is the wearer and John is an owner.  John is not wearing a collar.  John turns on Auto in Jane's collar and expects his session to auto-accept her hug requests.  Except it doesn't.  Average users often know very little about how permissions work.

2024-06-27 02:17 UTC, RosalynRussell commented
What I am hearing is it needs to be very clear that it's auto-ACCEPT. And in fairness, Pingout, we were communicating slowly due to me being on vacation and checking my email literally once a day. And, well, you did tell me that you tried a "Owner Initiated animation" in just the second message after the toggle was added, despite later learning you had no collar with which to initiate a animation...I think you mean you ordered it, but it was the sub's collar initiating it.

After talking with Medea, the button is now "▢ Auto Acc." with "Auto Acc. will auto accept animation permission from trusted or owners." in the prompt. If you think that's not enough, well....
[18:01] Rosalyn: It does fit. You think that will be good enough to deal with Pingout and Silkie's issue?
[18:01] Medea: Yeah I think so
[18:01] Rosalyn: Right, I'm quoting that.
...take it up with Medea.

2024-07-13 17:11 UTC, Medea-Destiny requested changes
Code looks good to me, but there are a couple of indenting issues I'd like to see fixed. See lines: 330-337, 338, 435, 498-523

2024-07-13 17:46 UTC, SilkieSabra commented
Just to outline these specs clearly, and offer a chance to correct my conception of this now:  There will be an Auto-Acc. button as an option in the Couples menu in the collar, that will apply only to the wearer, not to the owner.  If the owner is not wearing a collar, of course they will not be able to use the button in a collar they are not wearing.  **The owner does *not* need to be wearing a collar for auto-accept to work on the wearer from the wearer's collar.**  That would address my issue about buttons that don't appear to work.  If I don't get why anyone would want a couples animation to work when one party in the couple is not present, not alert or not willing, that's not an objection to having the feature for those who do get it.  A lot of "nots".

2024-07-16 15:36 UTC, RosalynRussell commented
Medea: I fixed the indentation. It was looking right in N++ but apparently as I copied in and out of N++ and SL the difference between tabs and spaces was lost. Everything should be indented right now.

Silkie: The Auto Acc button will auto-accept any couples pose request from a trusted or owner. You know, the pop-up asking permission to pose. That's what will be "auto-accepted" (in reality it's never sent, bypassed beforehand behind the scenes, but the easy explanation is that that pop-up is auto-accepted). If you trust the person who sent that pop-up, and auto is on, the pop-up won't happen. Obviously, at this point, the only way to initiate an oc_couples request is from a collar. So if I go into my collar, click poses, couples, hug, and select you, my collar sends the request. If your collar trusts me and auto is on, it does it all in the background, my collar telling your collar to animate you on my collar's behalf, meaning my collar does not need to ask permission to animate you. If I am not trusted, auto is off, or you have no collar, the permission pop-up appears, and my collar animates you as before.

In the future, the dominant hud may have oc_couples in it, so I could use my hud to initiate that request, bypassing my need for a collar, or if your hud/collar initiated the pose, to auto-accept your hud/collar's request. Having no reason to use the hud myself, I am unsure of it's current capabilities or how much work it will take to put oc_couples into it.

To be clear, when I say "initiate", I mean the collar sending the request. If I walk up to my slave, lily, and type "/1 li hug ro", Lily's collar initiates the pose request. Not me, or my collar. I'm starting to think I failed to properly explain what I mean by "initiated" and it was being confused with what I'd call "ordered". In the above hypothetical, I _ordered_ lily's collar to _initiate_ the hug pose with me. It's then up to my collar to auto-accept that request, and if it does not, either because it doesn't exist, I don't trust her, or auto is off, her collar backs up and initiates a permission request like before.

2024-07-18 01:11 UTC, Medea-Destiny approved these changes
We really shouldn't have mixed brace types in a single script but no big deal, fixing brace style is a future project anyway. Rosalyn favours a K&R brace style (as I do) but most of the 8.x codebase uses 1tb. This is all a matter of taste but the 1tb style does seem to put a lot of people off, and moving everything over to K&R in the near future seems like a good idea.

2024-07-18 01:17 UTC, Pingout approved these changes
We did quite a few testing scenarios, and it worked the way it was intended.

We should update the Animations page in the website and clarify in the Changelog. I think we need to be clear that the Auto Acc. will auto accept animation permission from trusted or owners who are wearing a collar

2024-07-18 19:43 UTC, merged